### PR TITLE
Fix BLE semaphore leak and improve SerialBLEInterface

### LINKED ISSUE #746: Companion firmware v1.8.1 keeps crashing on a Heltec T114
I've installed Companion Firmware v1.8.1 on my HeltecT114, but it is not usable, because it freezes up and terminates the Bluetooth connection every 1 or 2 minutes. The same T114 hardware runs fine with companion firmware v1.7.4.
I have no problems running Companion Firmware v1.8.1 on my Heltec V3.

Please let me know is there is any information I can provide to help find the cause  of this issue.

### PR DESCRIPTION
**Pull request by liquidraver**
TL;DR
This PR fixes a critical semaphore leak in Bluefruit that cause device lockups with iOS, and completely refactor SerialBLEInterface to handle the messy reality (understatement) of BLE connections with our dear friends SoftDevice and Bluefruit.

(hopefully) Resolves #746 #915 and #1067

I try to write down the key points that changed, sorry for the diff mess, I needed to rearrange serialbleinterface for better visibility/flow trace for myself

If anyone is interested in the whole debug process that is going on for weeks, there are a lot to read on discord in the thread: https://discord.com/channels/1343693475589263471/1437565846435139668
A huge thanks to everyone who has been testing it and sticking with us through all the reflashing and tweaks!

The Semaphore Leak (The Big One)
Root Cause: When the BT disconnects unexpectedly (supervision timeout, out of range, etc.), the BLE_GATTS_EVT_HVN_TX_COMPLETE event may never fire. This leaves Bluefruit's _hvn_sem counting semaphore in a decremented state. Since BLEConnection objects are reused (destructor never called), the semaphore count is never restored. After a few disconnects, all semaphore counts are exhausted and notify() blocks forever resulting in device lockup.
Added "patch_bluefruit.py" build script that patches the Bluefruit library at compile time (massive thx to Liam for figuring out in the first place and oltaco for refining it)

Connection State Management
- Added "_conn_handle" to track the active connection handle (always the same, but more reliable to track the state)
- "isValidConnection()" method validates handle matches and connection is actually connected
- All callbacks check "isValidConnection()" before processing
- "requireWaitingForSecurity" parameter prevents race conditions during pairing / rapid disconnects eg. someone is at the edge of BT range (...or repeatedly slams the microwave door on the phone)
  * Rejects duplicate onSecured() callbacks
  * Prevents stale callbacks from previous connections
  * Ensures connection parameters are only updated once per connection
- "isConnected()" now checks both "_isDeviceConnected" AND "Bluefruit.connected() > 0" to prevent false positives

Queue Management
- Send queue handles partial writes and connection loss gracefully
- Overflow protection: drains BLE buffer if frame exceeds "MAX_FRAME_SIZE" (thanks to spacepc-de for the idea, this Supersedes PR: #872)
- Separate send_queue and recv_queue (both size 12, up from 4)
- Receive queue populated in onBleUartRX() callback, consumed in checkRecvFrame() (callback-driven, not polling)
- Proper queue shifting functions (shiftSendQueueLeft, shiftRecvQueueLeft)

Connection Parameter Hell
iOS ignores Peripheral Preferred Connection Parameters (PPCP) (why? because *beep* you, I know it better, that's why!)
Explicitly set connection parameters in two places:
- PPCP: Sets preferred params
- Explicit request an update (in onSecured)

Parameters: 15-30ms interval, 0 latency, 2s supervision timeout. - conforms https://developer.apple.com/accessories/Accessory-Design-Guidelines.pdf
(We can increase latency if we want to squeeze a little more out of our battery, but it's miniscule compared to LoRa's consumption)

Advertising Watchdog
Advertising can silently stop (BLE stack bug, SoftDevice magic, Bluefruit moodswings, etc.) Device becomes undiscoverable until BT disable/enable.
Health check in checkRecvFrame():
- Runs every 10 seconds and restores advertising
This is needed because we rely on Bluefruit.Advertising.restartOnDisconnect(true)
The SoftDevice manages a BLE state machine. Calling sd_ble_gap_adv_start() at the wrong time (e.g., while advertising is still stopping, during connection establishment, or before proper cleanup) can return BLE_ERROR_INVALID_STATE or cause unpredictable behavior.
Using restartOnDisconnect(true) is the proper way but there were edge cases when the advertisement did not start. This is the best solution choosing from the two methods.
- isAdvertising() method uses sd_ble_gap_adv_addr_get() to detect advertising state

Connection stuff
- onPairingComplete(): Disconnects if pairing fails
- disconnect(): New method to explicitly disconnect via sd_ble_gap_disconnect()

TX
- Partial write detection: if bleuart.write() returns less than frame length, frame is dropped (corrupted)
- Connection loss detection: if write fails and connection is lost, frame is dropped

RX
- Overflow protection: drains buffer if available > MAX_FRAME_SIZE
- Queue full protection: drains remaining data if queue full

Optional:
// Bluefruit.autoConnLed(false); - if uncommented, we can do whatever else we want with the BT led.

### CODE REVIEW

**Comment by liquidraver** [comment]
@fdlamotte Could you please review this?

**Comment by recrof** [comment]
just my 2 cents: this change was tested pretty extensively with various radios by 10s of people, so it gets seal of approval from me.

**Comment by liquidraver** [comment]
I can try to make the commits cleaner, but I'm not a git magician, hope I won't mess this up :)

**Comment by fdlamotte** [comment]
Cool changes, that's really clean for integration !

**Comment by oltaco** [comment]
Really nice, we've been testing this code for a while now and know it works well.
Awesome clean rebase and squash, if only more PRs looked like this 🥇 

I know this is a pedantic nitpick on my part, but there are a lot of unnecessary casts which maybe hurt readability and are a bit out of step with the rest of the codebase imo. Just my 2c.

File: src/helpers/nrf52/SerialBLEInterface.cpp [hunk 1]
```diff
@@ -1,193 +1,353 @@
...
+    instance->clearBuffers();
+  }
 }
 
 void SerialBLEInterface::onDisconnect(uint16_t connection_handle, uint8_t reason) {
-  BLE_DEBUG_PRINTLN("SerialBLEInterface: disconnected reason=%d", reason);
-  if(instance){
-    instance->_isDeviceConnected = false;
-    instance->startAdv();
+  BLE_DEBUG_PRINTLN("SerialBLEInterface: disconnected handle=0x%04X reason=%u", connection_handle, (unsigned)reason);
```
Comment (oltaco) [inline src/helpers/nrf52/SerialBLEInterface.cpp]: reason is already uint8_t, so the cast is unnecessary.

File: src/helpers/nrf52/SerialBLEInterface.cpp [hunk 2]
```diff
@@ -1,193 +1,353 @@
...
+
+void SerialBLEInterface::onBLEEvent(ble_evt_t* evt) {
+  if (!instance) return;
+  
+  if (evt->header.evt_id == BLE_GAP_EVT_CONN_PARAM_UPDATE_REQUEST) {
+    uint16_t conn_handle = evt->evt.gap_evt.conn_handle;
+    if (instance->isValidConnection(conn_handle)) {
+      BLE_DEBUG_PRINTLN("CONN_PARAM_UPDATE_REQUEST: handle=0x%04X, min_interval=%u, max_interval=%u, latency=%u, timeout=%u",
+                       conn_handle,
+                       (unsigned)evt->evt.gap_evt.params.conn_param_update_request.conn_params.min_conn_interval,
```
Comment (oltaco) [inline src/helpers/nrf52/SerialBLEInterface.cpp]: same with these ones

**Review by oltaco — CHANGES_REQUESTED** [review]
@fdlamotte knows best, but I think maybe removing the unnecessary casts would help readability and keep it more in step with the rest of the codebase.

File: src/helpers/nrf52/SerialBLEInterface.cpp (hunk 1 above)
Comment (liquidraver) [reply src/helpers/nrf52/SerialBLEInterface.cpp]: right, removed

File: src/helpers/nrf52/SerialBLEInterface.cpp (hunk 2 above)
Comment (liquidraver) [reply src/helpers/nrf52/SerialBLEInterface.cpp]: removed this too

**Comment by oltaco** [comment]
@liquidraver Very nice,  looks much more neat and tidy to me. 👍

I'm on phone at the moment, is the advertising check stuff new? I'm not familiar sd_ble_gap_adv_addr_get

**Comment by liquidraver** [comment]
> @liquidraver Very nice, looks much more neat and tidy to me. 👍
> 
> I'm on phone at the moment, is the advertising check stuff new? I'm not familiar sd_ble_gap_adv_addr_get

sd_ble_gap_adv_addr_get is just used to check if we are advertising when we should (not connected, no handle, but enabled, etc). that command gives back error if we are not advertising so good for checking :)
